package uk.ac.lkl.cram.ui.obsolete;

import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.ParseException;
import javax.swing.JFormattedTextField;
import javax.swing.JFormattedTextField.AbstractFormatterFactory;
import javax.swing.JFrame;
import javax.swing.JSpinner;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import uk.ac.lkl.cram.model.AELMTest;
import uk.ac.lkl.cram.model.TLActivity;

/**
 *
 * @author Bernard Horan
 */
@SuppressWarnings({"serial", "ClassWithoutLogger"})
public class TLAWizardPanel extends javax.swing.JPanel {
    private TLActivity tlActivity;
    
    /**
     * Creates new form TLAWizardPanel
     * @param tla 
     */
    public TLAWizardPanel(TLActivity tla) {
	this.tlActivity = tla;
        initComponents();
	
	tlActivity.getLearningType().addPropertyChangeListener(new PropertyChangeListener() {

	    @Override
	    public void propertyChange(PropertyChangeEvent pce) {
		learningTypeSpinnerChanged();
	    }
	});	
	
	acquisitionSpinner.setValue(tlActivity.getLearningType().getAcquisition());
        acquisitionSpinner.addChangeListener(new ChangeListener() {

	    @Override
	    public void stateChanged(ChangeEvent ce) {
		JSpinner source = (JSpinner) ce.getSource();
                int aquisition = (Integer) source.getValue();
                tlActivity.getLearningType().setAcquisition(aquisition);			    
	    }
	});
	
	discussionSpinner.setValue(tlActivity.getLearningType().getDiscussion());
        discussionSpinner.addChangeListener(new ChangeListener() {

	    @Override
	    public void stateChanged(ChangeEvent ce) {
		JSpinner source = (JSpinner) ce.getSource();
                int discussion = (Integer) source.getValue();
                tlActivity.getLearningType().setDiscussion(discussion);	
	    }
	});
	
        inquirySpinner.setValue(tlActivity.getLearningType().getInquiry());
	inquirySpinner.addChangeListener(new ChangeListener() {

	    @Override
	    public void stateChanged(ChangeEvent ce) {
		JSpinner source = (JSpinner) ce.getSource();
                int inquiry = (Integer) source.getValue();
                tlActivity.getLearningType().setInquiry(inquiry);			    
	    }
	});
	
        practiceSpinner.setValue(tlActivity.getLearningType().getPractice());
	practiceSpinner.addChangeListener(new ChangeListener() {

	    @Override
	    public void stateChanged(ChangeEvent ce) {
		JSpinner source = (JSpinner) ce.getSource();
                int practice = (Integer) source.getValue();
                tlActivity.getLearningType().setPractice(practice);			    
	    }
	});
	
        productionSpinner.setValue(tlActivity.getLearningType().getProduction());
	productionSpinner.addChangeListener(new ChangeListener() {

	    @Override
	    public void stateChanged(ChangeEvent ce) {
		JSpinner source = (JSpinner) ce.getSource();
                int production = (Integer) source.getValue();
                tlActivity.getLearningType().setProduction(production);			    
	    }
	});
	
        
	
        final JFormattedTextField.AbstractFormatter learningFieldFormatter = new JFormattedTextField.AbstractFormatter() {

            @Override
            public Object stringToValue(String string) throws ParseException {
                return string;
            }

            @Override
            public String valueToString(Object o) throws ParseException {
                return String.valueOf(o) + '%';
            }
        };
        AbstractFormatterFactory aff = new JFormattedTextField.AbstractFormatterFactory() {

            @Override
            public JFormattedTextField.AbstractFormatter getFormatter(JFormattedTextField jftf) {
                return learningFieldFormatter;
            }
        };
        totalLearningTypeField.setFormatterFactory(aff);
        learningTypeSpinnerChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        learningExperiencePanel = new javax.swing.JPanel();
        learningTypePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalLearningTypeField = new javax.swing.JFormattedTextField();
        discussionSpinner = new javax.swing.JSpinner();
        inquirySpinner = new javax.swing.JSpinner();
        acquisitionSpinner = new javax.swing.JSpinner();
        practiceSpinner = new javax.swing.JSpinner();
        productionSpinner = new javax.swing.JSpinner();

        learningExperiencePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Nature of Learning Experience"));

        org.jdesktop.layout.GroupLayout learningExperiencePanelLayout = new org.jdesktop.layout.GroupLayout(learningExperiencePanel);
        learningExperiencePanel.setLayout(learningExperiencePanelLayout);
        learningExperiencePanelLayout.setHorizontalGroup(
            learningExperiencePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 261, Short.MAX_VALUE)
        );
        learningExperiencePanelLayout.setVerticalGroup(
            learningExperiencePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 418, Short.MAX_VALUE)
        );

        learningTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("% each learning type it elicits"));

        jLabel1.setText("Acquisition:");

        jLabel2.setText("Inquiry:");

        jLabel3.setText("Discussion:");

        jLabel4.setText("Practice:");

        jLabel5.setText("Production:");

        totalLearningTypeField.setEditable(false);
        totalLearningTypeField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        discussionSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        discussionSpinner.setBounds(new java.awt.Rectangle(0, 0, 37, 28));

        inquirySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        inquirySpinner.setBounds(new java.awt.Rectangle(0, 0, 37, 28));

        acquisitionSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        acquisitionSpinner.setBounds(new java.awt.Rectangle(0, 0, 37, 28));

        practiceSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        practiceSpinner.setBounds(new java.awt.Rectangle(0, 0, 37, 28));

        productionSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        productionSpinner.setBounds(new java.awt.Rectangle(0, 0, 37, 28));

        org.jdesktop.layout.GroupLayout learningTypePanelLayout = new org.jdesktop.layout.GroupLayout(learningTypePanel);
        learningTypePanel.setLayout(learningTypePanelLayout);
        learningTypePanelLayout.setHorizontalGroup(
            learningTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(learningTypePanelLayout.createSequentialGroup()
                .add(learningTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(totalLearningTypeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(learningTypePanelLayout.createSequentialGroup()
                        .add(learningTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jLabel4)
                            .add(jLabel5))
                        .add(0, 0, 0)
                        .add(learningTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(acquisitionSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(inquirySpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(discussionSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(practiceSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(productionSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(185, 185, 185))
        );
        learningTypePanelLayout.setVerticalGroup(
            learningTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(learningTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(learningTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(acquisitionSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(12, 12, 12)
                .add(learningTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(inquirySpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(0, 0, 0)
                .add(learningTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(discussionSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(learningTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(practiceSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .add(0, 0, 0)
                .add(learningTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(productionSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .add(0, 0, 0)
                .add(totalLearningTypeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(learningTypePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(49, 49, 49)
                .add(learningExperiencePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(learningExperiencePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(learningTypePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner acquisitionSpinner;
    private javax.swing.JSpinner discussionSpinner;
    private javax.swing.JSpinner inquirySpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel learningExperiencePanel;
    private javax.swing.JPanel learningTypePanel;
    private javax.swing.JSpinner practiceSpinner;
    private javax.swing.JSpinner productionSpinner;
    private javax.swing.JFormattedTextField totalLearningTypeField;
    // End of variables declaration//GEN-END:variables

    private void learningTypeSpinnerChanged() {
        int totalLearningType = (Integer) acquisitionSpinner.getValue();
        totalLearningType += (Integer) inquirySpinner.getValue();
        totalLearningType += (Integer) discussionSpinner.getValue();
        totalLearningType += (Integer) productionSpinner.getValue();
        totalLearningType += (Integer) practiceSpinner.getValue();
        totalLearningTypeField.setValue(totalLearningType);
        Color fieldColour; 
        if (totalLearningType == 100) {
            fieldColour = Color.GREEN;
        } else {
            fieldColour = Color.RED;
        }
        totalLearningTypeField.setForeground(fieldColour);
    }
    
    public static void main(String args[]) {
        
        final JFrame frame = new JFrame("TLA Wizard Panel");
        frame.add(new TLAWizardPanel(AELMTest.populateModule().getTLALineItems().get(0).getActivity()));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                frame.setVisible(true);
            }
        });
    }

}
