/*
 * Copyright 2014 London Knowledge Lab, Institute of Education.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.ac.lkl.cram.ui.wizard;

import javax.swing.JPanel;

/**
 * This class represents the visual aspects of the first step in the TLA creator
 * wizard. The visual rendering consists of two radio buttons to decide whether
 * to start from scratch or to use a pre-existing TLA.
 * @see StartWizardPanel
 * @version $Revision$
 * @author Bernard Horan
 */
//$Date$ 
@SuppressWarnings({"serial", "ClassWithoutLogger"})
public class StartVisualPanel extends JPanel {

    /**
     * Creates new form StartVisualPanel
     */
    public StartVisualPanel() {
        initComponents();
        predefinedRadioButton.setSelected(true);
    }

    @Override
    public String getName() {
        return "Create Teaching & Learning Activity";
    }

    public boolean isVanilla() {
        return vanillaRadioButton.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        predefinedRadioButton = new javax.swing.JRadioButton();
        vanillaRadioButton = new javax.swing.JRadioButton();

        buttonGroup1.add(predefinedRadioButton);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("uk/ac/lkl/cram/ui/wizard/Bundle"); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(predefinedRadioButton, bundle.getString("USE PRE-DEFINED")); // NOI18N

        buttonGroup1.add(vanillaRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(vanillaRadioButton, bundle.getString("START FROM SCRATCH")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(predefinedRadioButton)
                    .addComponent(vanillaRadioButton)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(predefinedRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vanillaRadioButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton predefinedRadioButton;
    private javax.swing.JRadioButton vanillaRadioButton;
    // End of variables declaration//GEN-END:variables
}
