package uk.ac.lkl.cram.ui.wizard;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.logging.Logger;
import javax.swing.JPanel;
import uk.ac.lkl.cram.model.LearnerFeedback;
import uk.ac.lkl.cram.model.StudentTeacherInteraction;
import uk.ac.lkl.cram.model.TLActivity;

/**
 * $Date: $
 * @author Bernard Horan
 */
public final class TLAPropertiesVisualPanel extends JPanel {
    private static final Logger LOGGER = Logger.getLogger(TLAPropertiesVisualPanel.class.getName());

    private final TLActivity tlActivity;

    /**
     * Creates new form TLAPropertiesVisualPanel
     * @param tla 
     */
    public TLAPropertiesVisualPanel(TLActivity tla) {
	this.tlActivity = tla;
	initComponents();
	tlActivity.addPropertyChangeListener(new PropertyChangeListener() {

	    @Override
	    public void propertyChange(PropertyChangeEvent pce) {
		String property = pce.getPropertyName();
		if (property.equals(TLActivity.PROP_NAME)) {
		    tlActivityNameChanged();
		}
	    }
	});
	
	//Radio Buttons	
	ActionListener feedbackListener = new ActionListener() {

	    @Override
	    public void actionPerformed(ActionEvent ae) {
		String actionCommand = ae.getActionCommand();
		LearnerFeedback lf = LearnerFeedback.valueOf(actionCommand);
		tlActivity.setLearnerFeedback(lf);
	    }
	};
	teacherFeedbackRB.addActionListener(feedbackListener);
	teacherFeedbackRB.setActionCommand(LearnerFeedback.TUTOR.name());
	peerFeedbackRB.addActionListener(feedbackListener);
	peerFeedbackRB.setActionCommand(LearnerFeedback.PEER_ONLY.name());
	telFeedbackRB.addActionListener(feedbackListener);
	telFeedbackRB.setActionCommand(LearnerFeedback.TEL.name());
	noFeedbackRB.addActionListener(feedbackListener);
	noFeedbackRB.setActionCommand(LearnerFeedback.NONE.name());
	LearnerFeedback lf = tlActivity.getLearnerFeedback();
	switch (lf) {
	    case TUTOR: {
		teacherFeedbackRB.setSelected(true);
		break;
	    }
	    case PEER_ONLY: {
		peerFeedbackRB.setSelected(true);
		break;
	    }
	    case TEL: {
		telFeedbackRB.setSelected(true);
		break;
	    }
	    case NONE: {
		noFeedbackRB.setSelected(true);
		break;
	    }
	}
	
	//CheckBoxes	
	final StudentTeacherInteraction sti = tlActivity.getStudentTeacherInteraction();
	independentLearningCB.addItemListener(new ItemListener() {

	    @Override
	    public void itemStateChanged(ItemEvent ie) {
		boolean selected = ie.getStateChange() == ItemEvent.SELECTED;
		sti.setTutorSupported(!selected);
	    }
	});
	independentLearningCB.setSelected(!sti.isTutorSupported());
	onlineCB.addItemListener(new ItemListener() {

	    @Override
	    public void itemStateChanged(ItemEvent ie) {
		boolean selected = ie.getStateChange() == ItemEvent.SELECTED;
		sti.setOnline(selected);
	    }
	});
	onlineCB.setSelected(sti.isOnline());
	locationSpecificCB.addItemListener(new ItemListener() {

	    @Override
	    public void itemStateChanged(ItemEvent ie) {
		boolean selected = ie.getStateChange() == ItemEvent.SELECTED;
		sti.setLocationSpecific(selected);
	    }
	});
	locationSpecificCB.setSelected(sti.isLocationSpecific());
	timeSpecificCB.addItemListener(new ItemListener() {

	    @Override
	    public void itemStateChanged(ItemEvent ie) {
		boolean selected = ie.getStateChange() == ItemEvent.SELECTED;
		sti.setTimeSpecific(selected);
	    }
	});
	timeSpecificCB.setSelected(sti.isTimeSpecific());
	
	
    }

    @Override
    public String getName() {
	return "Enter TLA Properties";
    }
    
    private void tlActivityNameChanged() {
	tlaNameField.setText(tlActivity.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        feedbackBG = new javax.swing.ButtonGroup();
        tlaNamePanel = new javax.swing.JPanel();
        tlaNameField = new javax.swing.JTextField();
        feedbackPanel = new javax.swing.JPanel();
        teacherFeedbackRB = new javax.swing.JRadioButton();
        peerFeedbackRB = new javax.swing.JRadioButton();
        telFeedbackRB = new javax.swing.JRadioButton();
        noFeedbackRB = new javax.swing.JRadioButton();
        studentInteractionPanel = new javax.swing.JPanel();
        independentLearningCB = new javax.swing.JCheckBox();
        locationSpecificCB = new javax.swing.JCheckBox();
        onlineCB = new javax.swing.JCheckBox();
        timeSpecificCB = new javax.swing.JCheckBox();

        tlaNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(TLAPropertiesVisualPanel.class, "TLAPropertiesVisualPanel.tlaNamePanel.border.title"))); // NOI18N

        tlaNameField.setEnabled(false);

        javax.swing.GroupLayout tlaNamePanelLayout = new javax.swing.GroupLayout(tlaNamePanel);
        tlaNamePanel.setLayout(tlaNamePanelLayout);
        tlaNamePanelLayout.setHorizontalGroup(
            tlaNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tlaNameField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        tlaNamePanelLayout.setVerticalGroup(
            tlaNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tlaNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        feedbackPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(TLAPropertiesVisualPanel.class, "TLAPropertiesVisualPanel.feedbackPanel.border.title"))); // NOI18N

        feedbackBG.add(teacherFeedbackRB);
        org.openide.awt.Mnemonics.setLocalizedText(teacherFeedbackRB, org.openide.util.NbBundle.getMessage(TLAPropertiesVisualPanel.class, "TLAPropertiesVisualPanel.teacherFeedbackRB.text")); // NOI18N

        feedbackBG.add(peerFeedbackRB);
        org.openide.awt.Mnemonics.setLocalizedText(peerFeedbackRB, org.openide.util.NbBundle.getMessage(TLAPropertiesVisualPanel.class, "TLAPropertiesVisualPanel.peerFeedbackRB.text")); // NOI18N

        feedbackBG.add(telFeedbackRB);
        org.openide.awt.Mnemonics.setLocalizedText(telFeedbackRB, org.openide.util.NbBundle.getMessage(TLAPropertiesVisualPanel.class, "TLAPropertiesVisualPanel.telFeedbackRB.text")); // NOI18N

        feedbackBG.add(noFeedbackRB);
        org.openide.awt.Mnemonics.setLocalizedText(noFeedbackRB, org.openide.util.NbBundle.getMessage(TLAPropertiesVisualPanel.class, "TLAPropertiesVisualPanel.noFeedbackRB.text")); // NOI18N

        javax.swing.GroupLayout feedbackPanelLayout = new javax.swing.GroupLayout(feedbackPanel);
        feedbackPanel.setLayout(feedbackPanelLayout);
        feedbackPanelLayout.setHorizontalGroup(
            feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherFeedbackRB)
                    .addComponent(peerFeedbackRB)
                    .addComponent(telFeedbackRB)
                    .addComponent(noFeedbackRB))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        feedbackPanelLayout.setVerticalGroup(
            feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherFeedbackRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peerFeedbackRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telFeedbackRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noFeedbackRB))
        );

        studentInteractionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(TLAPropertiesVisualPanel.class, "TLAPropertiesVisualPanel.studentInteractionPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(independentLearningCB, org.openide.util.NbBundle.getMessage(TLAPropertiesVisualPanel.class, "TLAPropertiesVisualPanel.independentLearningCB.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(locationSpecificCB, org.openide.util.NbBundle.getMessage(TLAPropertiesVisualPanel.class, "TLAPropertiesVisualPanel.locationSpecificCB.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(onlineCB, org.openide.util.NbBundle.getMessage(TLAPropertiesVisualPanel.class, "TLAPropertiesVisualPanel.onlineCB.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(timeSpecificCB, org.openide.util.NbBundle.getMessage(TLAPropertiesVisualPanel.class, "TLAPropertiesVisualPanel.timeSpecificCB.text")); // NOI18N

        javax.swing.GroupLayout studentInteractionPanelLayout = new javax.swing.GroupLayout(studentInteractionPanel);
        studentInteractionPanel.setLayout(studentInteractionPanelLayout);
        studentInteractionPanelLayout.setHorizontalGroup(
            studentInteractionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentInteractionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentInteractionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(independentLearningCB)
                    .addComponent(locationSpecificCB)
                    .addComponent(onlineCB)
                    .addComponent(timeSpecificCB))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        studentInteractionPanelLayout.setVerticalGroup(
            studentInteractionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentInteractionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(independentLearningCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onlineCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationSpecificCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeSpecificCB))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tlaNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentInteractionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(feedbackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tlaNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentInteractionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(feedbackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup feedbackBG;
    private javax.swing.JPanel feedbackPanel;
    private javax.swing.JCheckBox independentLearningCB;
    private javax.swing.JCheckBox locationSpecificCB;
    private javax.swing.JRadioButton noFeedbackRB;
    private javax.swing.JCheckBox onlineCB;
    private javax.swing.JRadioButton peerFeedbackRB;
    private javax.swing.JPanel studentInteractionPanel;
    private javax.swing.JRadioButton teacherFeedbackRB;
    private javax.swing.JRadioButton telFeedbackRB;
    private javax.swing.JCheckBox timeSpecificCB;
    private javax.swing.JTextField tlaNameField;
    private javax.swing.JPanel tlaNamePanel;
    // End of variables declaration//GEN-END:variables
    }
