package uk.ac.lkl.cram.ui;

import java.awt.Dimension;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.TableModel;
import uk.ac.lkl.cram.model.AELMTest;
import uk.ac.lkl.cram.model.Module;

/**
 * $Date$
 * $Revision$
 * @author Bernard Horan
 */
@SuppressWarnings("serial")
public class ModulePanel extends javax.swing.JPanel {
    private static final Logger LOGGER = Logger.getLogger(ModulePanel.class.getName());


    /**
     * Creates new form ModuleWizardPanel
     * @param module
     */
    public ModulePanel(final Module module) {
	initComponents();

	SelectAllAdapter saa = new SelectAllAdapter();
	
	moduleNameField.setText(module.getModuleName());
	moduleNameField.addFocusListener(saa);
	new TextFieldAdapter(moduleNameField) {

	    @Override
	    public void updateText(String value) {		
		module.setModuleName(value);
	    }
	};
	
	hourCountField.setValue(module.getTotalCreditHourCount());
	hourCountField.addFocusListener(saa);
	new FormattedTextFieldAdapter(hourCountField) {

	    @Override
	    public void updateValue(Object value) {
		int hourCount = (Integer) value;
		module.setTotalCreditHourCount(hourCount);
                }
	};
	
	weekCountField.setValue(module.getWeekCount());
	weekCountField.addFocusListener(saa);
	new FormattedTextFieldAdapter(weekCountField) {

	    @Override
	    public void updateValue(Object value) {
		int weekCount = (Integer) value;
		module.setWeekCount(weekCount);
	    }
	};
	
	tutorGroupSizeField.setValue(module.getTutorGroupSize());
	tutorGroupSizeField.addFocusListener(saa);
	new FormattedTextFieldAdapter(tutorGroupSizeField) {

	    @Override
	    public void updateValue(Object value) {
		int tutorGroupSize = (Integer) value;
		module.setTutorGroupSize(tutorGroupSize);
	    }
	};
	
	TableModel tableModel = new PresentationTableModel(module);
	presentationTable.setModel(tableModel);
	presentationTable.getColumnModel().getColumn(0).setPreferredWidth(70);
	presentationTable.getTableHeader().setPreferredSize(new Dimension(presentationTable.getColumnModel().getTotalColumnWidth(),36));

	

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moduleDetailsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tutorGroupSizeField = new javax.swing.JFormattedTextField();
        hourCountField = new javax.swing.JFormattedTextField();
        weekCountField = new javax.swing.JFormattedTextField();
        moduleNamePanel = new javax.swing.JPanel();
        moduleNameField = new javax.swing.JTextField();
        presentationPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        presentationTable = new javax.swing.JTable();

        moduleDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        jLabel3.setText("Number of Hours:");

        jLabel4.setText("Number of Weeks:");

        jLabel2.setText("Tutor Group Size:");

        tutorGroupSizeField.setColumns(4);
        tutorGroupSizeField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        hourCountField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        weekCountField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        org.jdesktop.layout.GroupLayout moduleDetailsPanelLayout = new org.jdesktop.layout.GroupLayout(moduleDetailsPanel);
        moduleDetailsPanel.setLayout(moduleDetailsPanelLayout);
        moduleDetailsPanelLayout.setHorizontalGroup(
            moduleDetailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(moduleDetailsPanelLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(moduleDetailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(moduleDetailsPanelLayout.createSequentialGroup()
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(hourCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(moduleDetailsPanelLayout.createSequentialGroup()
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(weekCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(moduleDetailsPanelLayout.createSequentialGroup()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(tutorGroupSizeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(0, 0, 0))
        );

        moduleDetailsPanelLayout.linkSize(new java.awt.Component[] {hourCountField, tutorGroupSizeField, weekCountField}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        moduleDetailsPanelLayout.setVerticalGroup(
            moduleDetailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(moduleDetailsPanelLayout.createSequentialGroup()
                .add(moduleDetailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tutorGroupSizeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(moduleDetailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(hourCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(moduleDetailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(weekCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        moduleNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Module Name"));

        org.jdesktop.layout.GroupLayout moduleNamePanelLayout = new org.jdesktop.layout.GroupLayout(moduleNamePanel);
        moduleNamePanel.setLayout(moduleNamePanelLayout);
        moduleNamePanelLayout.setHorizontalGroup(
            moduleNamePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(moduleNamePanelLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(moduleNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .add(0, 0, 0))
        );
        moduleNamePanelLayout.setVerticalGroup(
            moduleNamePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(moduleNamePanelLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(moduleNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        presentationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Runs"));

        presentationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Run", "Student Count", "Fee", "Junior Cost per day", "Senior Cost per Day"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        presentationTable.setEnabled(false);
        presentationTable.setFocusable(false);
        presentationTable.setRowSelectionAllowed(false);
        presentationTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        presentationTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(presentationTable);

        org.jdesktop.layout.GroupLayout presentationPanelLayout = new org.jdesktop.layout.GroupLayout(presentationPanel);
        presentationPanel.setLayout(presentationPanelLayout);
        presentationPanelLayout.setHorizontalGroup(
            presentationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(presentationPanelLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .add(0, 0, 0))
        );
        presentationPanelLayout.setVerticalGroup(
            presentationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(presentationPanelLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(presentationPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(moduleNamePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(0, 0, 0)
                        .add(moduleDetailsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(moduleDetailsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(moduleNamePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(presentationPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField hourCountField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel moduleDetailsPanel;
    private javax.swing.JTextField moduleNameField;
    private javax.swing.JPanel moduleNamePanel;
    private javax.swing.JPanel presentationPanel;
    private javax.swing.JTable presentationTable;
    private javax.swing.JFormattedTextField tutorGroupSizeField;
    private javax.swing.JFormattedTextField weekCountField;
    // End of variables declaration//GEN-END:variables
    
    
    
    
    public static void main(String args[]) {
        final JFrame frame = new JFrame("Module Panel");
	frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(new ModulePanel(AELMTest.populateModule()));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                frame.setVisible(true);
            }
        });
    }
}
