package uk.ac.lkl.cram.ui;

import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import uk.ac.lkl.cram.model.AELMTest;
import uk.ac.lkl.cram.model.Module;
import uk.ac.lkl.cram.model.ModulePresentation;

/**
 * $Date$
 * @author Bernard Horan
 */
public class ModuleWizardPanel extends javax.swing.JPanel {
    private static final Logger LOGGER = Logger.getLogger(ModuleWizardPanel.class.getName());

    private final Module module;

    /**
     * Creates new form ModuleWizardPanel
     * @param m
     */
    public ModuleWizardPanel(Module m) {
	this.module = m;
	initComponents();

	SelectAllAdapter saa = new SelectAllAdapter();
	
	moduleNameField.setText(module.getModuleName());
	moduleNameField.addFocusListener(saa);
	new TextFieldAdapter(moduleNameField) {

	    @Override
	    public void updateText(String value) {		
		module.setModuleName(value);
	    }
	};	
	
	hourCountField.setValue(new Long(module.getTotalCreditHourCount()));
	hourCountField.addFocusListener(saa);
	new FormattedTextFieldAdapter(hourCountField) {

	    @Override
	    public void updateValue(Object value) {
		long hourCount = (Long) value;
		module.setTotalCreditHourCount((int) hourCount);
	    }
	};
		
	weekCountField.setValue(new Long(module.getWeekCount()));
	weekCountField.addFocusListener(saa);
	new FormattedTextFieldAdapter(weekCountField) {

	    @Override
	    public void updateValue(Object value) {
		long weekCount = (Long) value;
		module.setWeekCount((int) weekCount);
	    }
	};
	
	tutorGroupSizeField.setValue(new Long(module.getTutorGroupSize()));
	tutorGroupSizeField.addFocusListener(saa);
	new FormattedTextFieldAdapter(tutorGroupSizeField) {

	    @Override
	    public void updateValue(Object value) {
		long tutorGroupSize = (Long) value;
		module.setTutorGroupSize((int) tutorGroupSize);
	    }
	};
		
	JFormattedTextField[] studentCountFields = new JFormattedTextField[3];
	studentCountFields[0] = presentation1StudentCountField;
	studentCountFields[1] = presentation2StudentCountField;
	studentCountFields[2] = presentation3StudentCountField;
	JFormattedTextField[] studentFeeFields = new JFormattedTextField[3];
	studentFeeFields[0] = presentation1StudentFeeField;
	studentFeeFields[1] = presentation2StudentFeeField;
	studentFeeFields[2] = presentation3StudentFeeField;
	JFormattedTextField[] juniorCostFields = new JFormattedTextField[3];
	juniorCostFields[0] = presentation1JuniorField;
	juniorCostFields[1] = presentation2JuniorField;
	juniorCostFields[2] = presentation3JuniorField;
	JFormattedTextField[] seniorCostFields = new JFormattedTextField[3];
	seniorCostFields[0] = presentation1SeniorField;
	seniorCostFields[1] = presentation2SeniorField;
	seniorCostFields[2] = presentation3SeniorField;
	int index = 0;
	for (final ModulePresentation modulePresentation : module.getModulePresentations()) {
	    studentCountFields[index].setValue(new Long(modulePresentation.getStudentCount()));
	    studentCountFields[index].addFocusListener(saa);
	    new FormattedTextFieldAdapter(studentCountFields[index]) {
		@Override
		public void updateValue(Object value) {
		    long studentCount = (Long) value;
		    modulePresentation.setStudentCount((int) studentCount);
		}
	    };
	    
	    studentFeeFields[index].setValue(new Long(modulePresentation.getFee()));
	    studentFeeFields[index].addFocusListener(saa);
	    new FormattedTextFieldAdapter(studentFeeFields[index]) {
		@Override
		public void updateValue(Object value) {
		    long fee = (Long) value;
		    modulePresentation.setFee((int) fee);
		}
	    };
	    
	    juniorCostFields[index].setValue(new Long(modulePresentation.getJuniorCost()));
	    juniorCostFields[index].addFocusListener(saa);
	    new FormattedTextFieldAdapter(juniorCostFields[index]) {
		@Override
		public void updateValue(Object value) {
		    long cost = (Long) value;
		    modulePresentation.setJuniorCost((int) cost);
		}
	    };
	    
	    seniorCostFields[index].setValue(new Long(modulePresentation.getSeniorCost()));
	    seniorCostFields[index].addFocusListener(saa);
	    new FormattedTextFieldAdapter(seniorCostFields[index]) {
		@Override
		public void updateValue(Object value) {
		    long cost = (Long) value;
		    modulePresentation.setSeniorCost((int) cost);
		}
	    };
	    
	    index++;
	}
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moduleDetailsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tutorGroupSizeField = new javax.swing.JFormattedTextField();
        hourCountField = new javax.swing.JFormattedTextField();
        weekCountField = new javax.swing.JFormattedTextField();
        moduleNamePanel = new javax.swing.JPanel();
        moduleNameField = new javax.swing.JTextField();
        presentationPanel = new javax.swing.JPanel();
        presentationsTitle = new org.jdesktop.swingx.JXLabel();
        studentCountTitle = new org.jdesktop.swingx.JXLabel();
        studentFeeTitle = new org.jdesktop.swingx.JXLabel();
        juniorCostTitle = new org.jdesktop.swingx.JXLabel();
        seniorCostTitle = new org.jdesktop.swingx.JXLabel();
        presentation1Label = new javax.swing.JLabel();
        presentation1StudentCountField = new javax.swing.JFormattedTextField();
        presentation1StudentFeeField = new javax.swing.JFormattedTextField();
        presentation1JuniorField = new javax.swing.JFormattedTextField();
        presentation1SeniorField = new javax.swing.JFormattedTextField();
        presentation2Label = new javax.swing.JLabel();
        presentation2StudentCountField = new javax.swing.JFormattedTextField();
        presentation2StudentFeeField = new javax.swing.JFormattedTextField();
        presentation2JuniorField = new javax.swing.JFormattedTextField();
        presentation2SeniorField = new javax.swing.JFormattedTextField();
        presentation3Label = new javax.swing.JLabel();
        presentation3StudentCountField = new javax.swing.JFormattedTextField();
        presentation3StudentFeeField = new javax.swing.JFormattedTextField();
        presentation3JuniorField = new javax.swing.JFormattedTextField();
        presentation3SeniorField = new javax.swing.JFormattedTextField();

        moduleDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Details..."));

        jLabel3.setText("Number of Hours:");

        jLabel4.setText("Number of Weeks:");

        jLabel2.setText("Tutor Group Size:");

        tutorGroupSizeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tutorGroupSizeField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        hourCountField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        hourCountField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        weekCountField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        weekCountField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        org.jdesktop.layout.GroupLayout moduleDetailsPanelLayout = new org.jdesktop.layout.GroupLayout(moduleDetailsPanel);
        moduleDetailsPanel.setLayout(moduleDetailsPanelLayout);
        moduleDetailsPanelLayout.setHorizontalGroup(
            moduleDetailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(moduleDetailsPanelLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(moduleDetailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(moduleDetailsPanelLayout.createSequentialGroup()
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(hourCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(moduleDetailsPanelLayout.createSequentialGroup()
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(weekCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(moduleDetailsPanelLayout.createSequentialGroup()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(tutorGroupSizeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        moduleDetailsPanelLayout.linkSize(new java.awt.Component[] {hourCountField, tutorGroupSizeField, weekCountField}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        moduleDetailsPanelLayout.setVerticalGroup(
            moduleDetailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(moduleDetailsPanelLayout.createSequentialGroup()
                .add(moduleDetailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tutorGroupSizeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(moduleDetailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(hourCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(moduleDetailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(weekCountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        moduleNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Module Name"));

        org.jdesktop.layout.GroupLayout moduleNamePanelLayout = new org.jdesktop.layout.GroupLayout(moduleNamePanel);
        moduleNamePanel.setLayout(moduleNamePanelLayout);
        moduleNamePanelLayout.setHorizontalGroup(
            moduleNamePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(moduleNamePanelLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(moduleNameField)
                .add(0, 0, 0))
        );
        moduleNamePanelLayout.setVerticalGroup(
            moduleNamePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(moduleNamePanelLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(moduleNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        presentationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Runs"));
        presentationPanel.setLayout(new java.awt.GridLayout(4, 5));
        presentationPanel.add(presentationsTitle);

        studentCountTitle.setText("Student Count");
        studentCountTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        studentCountTitle.setLineWrap(true);
        presentationPanel.add(studentCountTitle);

        studentFeeTitle.setText("Student Fee");
        studentFeeTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        studentFeeTitle.setLineWrap(true);
        presentationPanel.add(studentFeeTitle);

        juniorCostTitle.setText("Junior Cost per Day");
        juniorCostTitle.setLineWrap(true);
        presentationPanel.add(juniorCostTitle);

        seniorCostTitle.setText("Senior Cost per Day");
        seniorCostTitle.setLineWrap(true);
        presentationPanel.add(seniorCostTitle);

        presentation1Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        presentation1Label.setText("Run 1:");
        presentationPanel.add(presentation1Label);

        presentation1StudentCountField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        presentation1StudentCountField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        presentationPanel.add(presentation1StudentCountField);

        presentation1StudentFeeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        presentation1StudentFeeField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        presentationPanel.add(presentation1StudentFeeField);

        presentation1JuniorField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        presentation1JuniorField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        presentationPanel.add(presentation1JuniorField);

        presentation1SeniorField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        presentation1SeniorField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        presentationPanel.add(presentation1SeniorField);

        presentation2Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        presentation2Label.setText("Run 2:");
        presentationPanel.add(presentation2Label);

        presentation2StudentCountField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        presentation2StudentCountField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        presentationPanel.add(presentation2StudentCountField);

        presentation2StudentFeeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        presentation2StudentFeeField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        presentationPanel.add(presentation2StudentFeeField);

        presentation2JuniorField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        presentation2JuniorField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        presentationPanel.add(presentation2JuniorField);

        presentation2SeniorField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        presentation2SeniorField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        presentationPanel.add(presentation2SeniorField);

        presentation3Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        presentation3Label.setText("Run 3:");
        presentationPanel.add(presentation3Label);

        presentation3StudentCountField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        presentation3StudentCountField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        presentationPanel.add(presentation3StudentCountField);

        presentation3StudentFeeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        presentation3StudentFeeField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        presentationPanel.add(presentation3StudentFeeField);

        presentation3JuniorField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        presentation3JuniorField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        presentationPanel.add(presentation3JuniorField);

        presentation3SeniorField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        presentation3SeniorField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        presentationPanel.add(presentation3SeniorField);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(presentationPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(moduleNamePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(0, 0, 0)
                        .add(moduleDetailsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(moduleDetailsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(moduleNamePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(presentationPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField hourCountField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.jdesktop.swingx.JXLabel juniorCostTitle;
    private javax.swing.JPanel moduleDetailsPanel;
    private javax.swing.JTextField moduleNameField;
    private javax.swing.JPanel moduleNamePanel;
    private javax.swing.JFormattedTextField presentation1JuniorField;
    private javax.swing.JLabel presentation1Label;
    private javax.swing.JFormattedTextField presentation1SeniorField;
    private javax.swing.JFormattedTextField presentation1StudentCountField;
    private javax.swing.JFormattedTextField presentation1StudentFeeField;
    private javax.swing.JFormattedTextField presentation2JuniorField;
    private javax.swing.JLabel presentation2Label;
    private javax.swing.JFormattedTextField presentation2SeniorField;
    private javax.swing.JFormattedTextField presentation2StudentCountField;
    private javax.swing.JFormattedTextField presentation2StudentFeeField;
    private javax.swing.JFormattedTextField presentation3JuniorField;
    private javax.swing.JLabel presentation3Label;
    private javax.swing.JFormattedTextField presentation3SeniorField;
    private javax.swing.JFormattedTextField presentation3StudentCountField;
    private javax.swing.JFormattedTextField presentation3StudentFeeField;
    private javax.swing.JPanel presentationPanel;
    private org.jdesktop.swingx.JXLabel presentationsTitle;
    private org.jdesktop.swingx.JXLabel seniorCostTitle;
    private org.jdesktop.swingx.JXLabel studentCountTitle;
    private org.jdesktop.swingx.JXLabel studentFeeTitle;
    private javax.swing.JFormattedTextField tutorGroupSizeField;
    private javax.swing.JFormattedTextField weekCountField;
    // End of variables declaration//GEN-END:variables
    
    
    public static void main(String args[]) {
        final JFrame frame = new JFrame("Module Wizard Panel");
	frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(new ModuleWizardPanel(AELMTest.populateModule()));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                frame.setVisible(true);
            }
        });
    }

    Module getModule() {
	return module;
    }
}
