/*
 * Copyright 2014 London Knowledge Lab, Institute of Education.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.ac.lkl.cram.ui;


import java.util.ResourceBundle;
import javax.swing.JButton;

/**
 * This class represents the startup dialog box that is presented to the user
 * when the application is started.
 * @version $Revision$
 * @author Bernard Horan
 */
//$Date$
@SuppressWarnings({"serial", "ClassWithoutLogger"})
public class StartupDialog extends javax.swing.JDialog {

    private static final ResourceBundle bundle = ResourceBundle.getBundle("uk/ac/lkl/cram/ui/Bundle");

    /**
     * Creates new form StartupDialog
     *
     * @param parent the parent of the dialog box
     * @param modal whether the dialog box is modal
     */
    public StartupDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        StringBuilder builder = new StringBuilder(10);
        builder.append("Build: ");
        builder.append(bundle.getString("build.version"));
        builder.append(" Date: ");
        builder.append(bundle.getString("build.date"));
        buildLabel.setText(builder.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        newModuleButton = new javax.swing.JButton();
        openModuleButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        buildLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Course Resource Appraisal Model");
        setResizable(false);

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uk/ac/lkl/cram/ui/resource/CRAM.png"))); // NOI18N
        getContentPane().add(iconLabel, java.awt.BorderLayout.CENTER);

        newModuleButton.setText("New Module...");
        jPanel1.add(newModuleButton);

        openModuleButton.setText("Open Module...");
        jPanel1.add(openModuleButton);

        quitButton.setText("Quit...");
        jPanel1.add(quitButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        buildLabel.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        buildLabel.setText("Build details");
        getContentPane().add(buildLabel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * For testing purposes only
     * @param args the command line arguments (ignored)
     */
    public static void main(String args[]) {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                StartupDialog dialog = new StartupDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buildLabel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newModuleButton;
    private javax.swing.JButton openModuleButton;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables

    JButton getNewModuleButton() {
        return newModuleButton;
    }

    JButton getOpenModuleButtion() {
        return openModuleButton;
    }

    JButton getQuitButton() {
        return quitButton;
    }
}
