
package uk.ac.lkl.cram.ui;

import java.awt.Component;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import uk.ac.lkl.cram.ui.table.ColumnGroup;
import uk.ac.lkl.cram.ui.table.GroupableTableHeader;
import javax.swing.table.TableColumnModel;
import uk.ac.lkl.cram.model.Module;

/**
 * $Date$
 * $Revision$
 * @author Bernard Horan
 */
public class TutorHoursPanel extends javax.swing.JPanel {

    /**
     * Creates new form TutorHoursPanel
     * @param module 
     */
    public TutorHoursPanel(Module module) {
	initComponents();
	tutorHoursTable.setModel(new TutorHoursTableModel(module));
	tutorHoursTable.setDefaultRenderer(String.class, new LineItemRenderer());

	tutorHoursTable.getColumnModel().getColumn(0).setPreferredWidth(150);
	TableColumnModel tableColumnModel = tutorHoursTable.getColumnModel();
	ColumnGroup g_2nd = new ColumnGroup("Preparation");
	g_2nd.add(tableColumnModel.getColumn(1));
	g_2nd.add(tableColumnModel.getColumn(2));
	g_2nd.add(tableColumnModel.getColumn(3));
	ColumnGroup g_3rd = new ColumnGroup("Support");
	g_3rd.add(tableColumnModel.getColumn(4));
	g_3rd.add(tableColumnModel.getColumn(5));
	g_3rd.add(tableColumnModel.getColumn(6));
	GroupableTableHeader tableHeader = new GroupableTableHeader(tableColumnModel);
	tableHeader.addColumnGroup(g_2nd);
	tableHeader.addColumnGroup(g_3rd);
	tutorHoursTable.setTableHeader(tableHeader);
	tableHeader.revalidate();
	setSize(tutorHoursTable.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tutorHoursTable = new javax.swing.JTable();

        tutorHoursTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Activity", "Run 1", "Run 2", "Run 3", "Run 1", "Run 2", "Run 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tutorHoursTable.setEnabled(false);
        tutorHoursTable.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(tutorHoursTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tutorHoursTable;
    // End of variables declaration//GEN-END:variables

    class LineItemRenderer extends DefaultTableCellRenderer {

	@Override
	public Component getTableCellRendererComponent(JTable table, Object value,
		boolean isSelected, boolean hasFocus, int row, int column) {

	    super.getTableCellRendererComponent(table, value, isSelected, hasFocus,
		    row, column);
	    //Bold the last row
	    if (row == table.getModel().getRowCount() - 1) {
		setFont(this.getFont().deriveFont(Font.ITALIC));
	    }

	    return this;
	}
    }
}
